### ISSUE TITLE
[Request] Minimize feature & Open in Browser button

### ISSUE THREAD

**Issue by KhaozFrost** [Blobanium/MCBrowser#7]
2 things that would be really nice to add would be a minimize feature where you could minimize the page but it still be active "in the background" and it just like minimize to a small button icon in the corner of screen (that could be moved around via config) to where you want it. (for the ability to quickly respond to chat messages or react to something in the game without having to reopen the whole browser. The 2nd would be a button in the browser itself that lets you open it like a normal weblink. (or even something like shift+clicking on the links opens external browser and regular clicking links opens ingame browser.

**Comment by Blobanium** [comment]
I believe the second one has already been added since [v1.0.0-Pre2](https://github.com/Blobanium/MCBrowser/releases/tag/v1.0.0-Pre2) if that's what your looking for. 

The first one however, might take some time to implement. Mainly due to how i have implemented the browser logic. However one of my contributors for this repo did reach out to me on discord and said they did manage to implement something like what you described. But however they haven't pushed that feature to their fork just yet.

**Comment by KhaozFrost** [comment]
> I believe the second one has already been added since [v1.0.0-Pre2](https://github.com/Blobanium/MCBrowser/releases/tag/v1.0.0-Pre2) if that's what your looking for.
> 
> The first one however, might take some time to implement. Mainly due to how i have implemented the browser logic. However one of my contributors for this repo did reach out to me on discord and said they did manage to implement something like what you described. But however they haven't pushed that feature to their fork just yet.

hope they will push it to their fork. really excited to be able to do the minimize thing.

**Comment by Blobanium** [comment]
added in [v1.0.0](https://github.com/Blobanium/MCBrowser/releases/tag/v1.0.0)
